"""Add qr_code and qr_data to tickets

Revision ID: 9156570cfff3
Revises: 5e6cbf2519f4
Create Date: 2026-02-07 00:22:23.246269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9156570cfff3'
down_revision = '5e6cbf2519f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ticket_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('qr_data', sa.String(length=255), nullable=True))
        batch_op.alter_column('payment_status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('tickets_ticket_number_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('tickets_verified_by_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('tickets_verified_by_fkey'), 'users', ['verified_by'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('tickets_ticket_number_key'), ['ticket_number'])
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               existing_nullable=True)
        batch_op.drop_column('qr_data')
        batch_op.drop_column('qr_code')

    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.alter_column('ticket_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
